### ISSUE TITLE
can we talk

### ISSUE THREAD

**Issue by ramazan5134** [Kizuno18/twitch-payloads-api-bot#1]
hello what is your telegram address?

**Comment by ramazan5134** [comment]
python main.py
exception: 'NoneType' object is not subscriptable 
how can ı fix it

**Comment by Kizuno18** [comment]
i dont use telegram
this error is common and can be supressed, it means when try to get token return none, prob it is your proxy, actually i dont think this script will work without some new lines of code.
its more for study.
